---
 
- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates (CentOS)
    dnf:
      update_cache: yes
    changed_when: false    
    when: ansible_distribution == "CentOS"
 
  - name: install updates (Ubuntu)
    apt:
      update_cache: yes
      changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:


  - name: add ssh key molotov to authorized key file
    tags: always
    authorized_key:
      user: molotov
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6SfokAoJ3pGZPOF26IKQ6uDR5p9sQzJTlFMrgd8yB8//wUJXXxLKRCcjNjtJWoROYCZH4ZfSItGclTWbZhZYI4bzVPJRWKODocGXGdWntsPL178rC1Sfp6qiJUaoYfkKfCc192RpF1fBZ4hFKtDvXiZy3zwRYhF334OB87pS5hII1IrPAG0+X6b53jdkOTk6a/EemmHJilqX9irHYQm/ND1T53ntpE6ciDWZOImxxo+9dzn1tZGBq6b3n2CA0KBTlc94Zf1d6YN81ZXCIzhZ0JAdHJbdjniZMzUAwf62rtNVSSJHoc8UoMkQWmhLLyZpHZVmN2pAqT+jeovnXEm5PwAPU7VOZCU6W2z2ZCLlN2dYcuEqGjbcdMjj+ii16Rzd+7wo2Bq1jYcqb+ilFrQ0+SOV8C/hiRoJDj4QaNqFZET2EJxs+85GsWUuYUatz7Y9ZJFsDktAq2BozwKARYMbU32tc5Va2R+OMFhm0sM8bq4EfvJTs8grFUInW+047cuKF237ws7j+Ppcyon97AgGMssLo4k39rFZuBq1BiR0r3p2B4THQMuPVzEKOFUBL41hv3CDt+OcD/ROnOV2uPj8cxAyao+jcBDCRcqVbXgs+Vfxxv4VlRoHGYhN5nBDLEK47NYLAFmsPNlU2Iu+sGvjdnwOtS4mmteK8WAUWWQaGpw== root@ansible"     


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive: 
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root  
 
- hosts: web_servers
  become: true
  tasks:
 
  - name: install httpd package (CentOS)
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"


  - name: install apache2 package (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: change hostnamelookup
    lineinfile: 
      path: /etc/apache2/apache2.conf
      regexp: '^HostnameLookups'
      line: HostnameLookups on
    when: ansible_distribution == "Debian"
    register: apache2  #register ist hier wichtig das es bei when: apache2.changed wieder aufgerufen wird

  - name: restart apache2 (Debian)    
    service:
      name: apache2
      state: restarted
    when: apache2.changed    # siehe register

- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb server package (CentOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install mariadb server
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
 
- hosts: file_servers
  become: true
  tasks:
 
  - name: install samba package
    package:
      name: samba
      state: latest
